### ISSUE TITLE
Download script does not work

### ISSUE THREAD

**Issue by AurisAudentis** [RMLio/rmlmapper-webapi-js#3]
The automatic downloadscript for rmlmapper.jar is no longer functional. -Mggeldho

**Comment by pheyvaer** [comment]
What is the error?

**Comment by AurisAudentis** [comment]
The steps I've taken to replicate the problem:
- run  npm i -g @rmlio/rmlmapper-webapi
- run rmlmapper-webapi

As specified by the README under CLI.
This results in output:
```
info: No path to an RMLMapper jar is defined.
No jar was found for the latest release. Please contact the developers.
```

**Comment by pheyvaer** [comment]
Should be fixed now. There was no jar at the latest release of the RMLMapper [here](https://github.com/RMLio/rmlmapper-java/releases/tag/v4.8.0). I just added it.

**Comment by AurisAudentis** [comment]
The error doesn't occur anymore now.
