### ISSUE TITLE
CLI usage - options

### ISSUE THREAD

**Issue by AurisAudentis** [RMLio/rmlmapper-webapi-js#4]
The options to specify the rmlmapper path and jar are not respected. Briefly looking in the code suggests the options are parsed, but not read into the config object at startup.

Workaround: the default path is still respected. This means the NPM install cannot be used, but a local install with self-built .jar can still work.
-mggeldho

**Comment by pheyvaer** [comment]
Could you add the specific command you are running?

**Comment by AurisAudentis** [comment]
Certainly. Both 'rmlmapper-webapi -r ./rmlmapper.jar' and 'rmlmapper-webapi --rmlmapper /home/maxiem/rmlmapper.jar' resulted in
`info: No path to an RMLMapper jar is defined.
No jar was found for the latest release. Please contact the developers.
`

Specifiying the path in a config.json file also results in the same errors (with an extra message stating your config file is being used).
